website: Update 'Contributing' page
gem5/new-website pull request #72
Opened 2023-07-26 02:18 UTC by BobbyRBruce

Updates the website contributing page to incorporate contribution guidelines stated within the gem5 repositories CONTRIBUTING.md file. The purpose of this is to make the website contributing guidelines the definitive guide and keep the gem5 repo's CONTRIBUTING.md file in-sync with the website.

This change also updates, where appropriate, the contributing guidelines to reflect new changes since moving to GitHub.

2023-07-26 17:53 UTC, powerjg commented
You may find this action helpful :).

https://github.com/marketplace/actions/repo-file-sync-action

We should probably put it in the gem5 repo and then sync to the website.

2023-07-26 18:50 UTC, powerjg requested changes
Just a few small things. Generally, it looks good.

Thanks for syncing these documents!

2023-07-26 18:50 UTC, powerjg commented on _pages/contributing.md
> +https://github.com/gem5/gem5/blob/stable/TAGS.yaml) for
Probably want to hold off on this for now.

2023-07-26 18:50 UTC, powerjg commented on _pages/contributing.md
> +The gem5 maintainers are a small group of developers who have been granted the ability to merge pull-requests into the gem5 `develop` branch.
```suggestion
The gem5 maintainers the individuals granted the ability to merge pull-requests into the gem5 `develop` branch.
```

2023-07-26 18:50 UTC, powerjg commented on _pages/contributing.md
> +A git "force push" (i.e., `git push --force`) is also acceptable if you wish to alter the commits locally in order to make the changes.
Should we add that we would prefer if people did a rebase and/or amend and force pushed instead of applying changes to the end, if at all possible?

2023-07-26 18:50 UTC, powerjg commented on _pages/contributing.md
> +* If choosing to not approve a PR, please state clearly why.
```suggestion
* If choosing to not approve a PR, please state clearly why.
When asking for changes, the comments should be specific and actionable.
```

2023-07-26 18:50 UTC, powerjg commented on _pages/contributing.md
> +
Putting this link would be good, too: https://google.github.io/eng-practices/review/reviewer/comments.html

2023-07-26 23:54 UTC, BobbyRBruce commented
Thanks @powerjg , I've addressed all your comments.

2023-07-27 00:05 UTC, powerjg approved these changes

2023-07-27 00:05 UTC, powerjg commented
Can you squash this into a single commit?

2023-07-27 00:13 UTC, BobbyRBruce commented
> Can you squash this into a single commit?

It paints me so much to do... I love the git history of the change :(.

Ok. it's done.

2023-07-27 00:14 UTC, merged